"""initial schema

Revision ID: 8941bb461b0c
Revises: 
Create Date: 2026-03-17 02:36:06.660991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8941bb461b0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('mandi', sa.String(length=100), nullable=True),
    sa.Column('price_modal', sa.Float(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('recorded_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('whatsapp', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp')
    )
    op.create_table('tenders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_hindi', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('whatsapp_summary', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=10), nullable=True),
    sa.Column('red_flags', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('alerted_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('tender_id', sa.String(length=50), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('response', sa.String(length=10), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('tenders')
    op.drop_table('suppliers')
    op.drop_table('price_logs')
    # ### end Alembic commands ###
